### PR TITLE
fixed reports formatting

### LINKED ISSUE #40: Specific user report text visualization issue
The way the text is formatted in the user specific reports in the reports class is not legible.

### PR DESCRIPTION
**Pull request by Jacksonball-jlb**
Fixes #40 

Added a better format to both clock in/out and hours:minutes columns

### CODE REVIEW

**Review by AungA07 — CHANGES_REQUESTED** [review]
make sure that the dates that are printed out are within start date and end date

**Comment by Jacksonball-jlb** [comment]
New addition fixes #39

**Review by AungA07 — APPROVED** [review]
It looks good now that you added the date checking 👍

**Review by LuisTheSup — APPROVED** [review]
Good Boy!

**Pull request merged**
